version: "3.8"

services:
  postgres_database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: our_database
      POSTGRES_USER: our_user
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - main_network

  api1:
    build: .
    env_file: .env
    command: bash -c "alembic upgrade head &&  uvicorn app.main:app --port=9000 --host=0.0.0.0 --reload --no-access-log"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - postgres_database
    networks:
      main_network:
        aliases:
          - api1-net

  api2:
    build: .
    env_file: .env
    command: bash -c "alembic upgrade head &&  uvicorn app.main:app --port=9000 --host=0.0.0.0 --reload --no-access-log"
    volumes:
      - .:/app
    ports:
      - "9001:9000"
    depends_on:
      - postgres_database
    networks:
      main_network:
        aliases:
          - api2-net

  api3:
    build: .
    env_file: .env
    command: bash -c "alembic upgrade head &&  uvicorn app.main:app --port=9000 --host=0.0.0.0 --reload --no-access-log"
    volumes:
      - .:/app
    ports:
      - "9002:9000"
    depends_on:
      - postgres_database
    networks:
      main_network:
        aliases:
          - api3-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '7000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:11
    depends_on:
      - api1
      - api2
      - api3
    networks:
      main_network:
        aliases:
          - nginx


networks:
  main_network:
    driver: bridge

volumes:
  postgres-data:
    external: false
