version: "3.8"

x-service-common: &service-common
  build: .
  env_file: .env
  command: bash -c "alembic upgrade head &&  uvicorn app.main:app --port=9000 --host=0.0.0.0 --reload --no-access-log"
  volumes:
    - .:/app
  depends_on:
    - postgres_database
  networks:
    - main_network

services:
  postgres_database:
#    https://habr.com/ru/articles/578744/
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: our_database
      POSTGRES_USER: our_user
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - main_network

  api1:
    <<: *service-common
    ports:
      - "9000:9000"

  api2:
    <<: *service-common
    ports:
      - "9001:9000"

  api3:
    <<: *service-common
    ports:
      - "9002:9000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - main_network

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: my-password

      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - "8081:8081"

networks:
  main_network:
    driver: bridge

volumes:
  postgres-data:
    external: false
