version: "3.8"

services:

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - describly
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  describly:
