[tool.poetry]
name = "AWESOME-FASTAPI-PROJECT"
version = "0.1.0"
description = ""
authors = [
    "Yaroslavshym <139383618+Yaroslavshym@users.noreply.github.com>",
    "Vasyl Kartychak https://github.com/smartguy-coder/AWESOME-FASTAPI-PROJECT",
    "Danylo Soldatenko <dansoldat9@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.104.1"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
