[tool.poetry]
name = "AWESOME-FASTAPI-PROJECT"
version = "0.1.0"
description = ""
authors = [
    "Yaroslavshym <139383618+Yaroslavshym@users.noreply.github.com>",
    "Vasyl Kartychak https://github.com/smartguy-coder/AWESOME-FASTAPI-PROJECT",
    "Illya Kartychak",
    "Kiril Lypenko",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.104.1"}
fastapi-versioning = "^0.10.0"
sentry-sdk = "^1.35.0"
sqlalchemy = "^2.0.23"
psycopg2 = "^2.9.9"
uvicorn = "^0.24.0.post1"
alembic = "^1.12.1"



[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
